version: '3'
services:
  agent:
      image: quay.io/ocpmetal/assisted-installer-agent:latest
      entrypoint: ["/usr/bin/agent","--host","wiremock","--port","8080", "--cluster-id", "11111111-1111-1111-1111-111111111111", "--interval", "5"]
      volumes:
        - ./logs:/var/log
        - /var/run/docker.sock:/var/run/docker.sock
        - /run/systemd/journal/socket:/run/systemd/journal/socket
        - /dev/log:/dev/log
      privileged: true
      container_name: agent_container
      environment:
        - PULL_SECRET_TOKEN=OpenShiftToken

  wiremock:
    image: "rodolpheche/wiremock"
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock
